### ISSUE TITLE
a jpg pic can't see watermark

### ISSUE THREAD

**Issue by idonkeyliu** [linyacool/blind-watermark#1]
after decode, Jpg can't see watermark. The pic is a vertical pic.
![ori](https://cloud.githubusercontent.com/assets/6152000/24130705/32b63476-0e25-11e7-994b-ce29d09ea513.jpg)

**Comment by linyacool** [comment]
Jpg format is lossy compression , you'd better use some lossless compression formats like bmp, png, gif.

**Comment by idonkeyliu** [comment]
OK, thank. I'll have a try.

**Comment by pxpy** [comment]
PS C:\Users\panxin\Desktop> python encode.py --image 3d.tif --watermark wm.png --result jm.tif
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "encode.py", line 54, in <module>
    main()
  File "encode.py", line 30, in main
    encode(img, wm, res, alpha)
  File "encode.py", line 39, in encode
    x, y = range(height / 2), range(width)
TypeError: 'float' object cannot be interpreted as an integer

**Comment by linyacool** [comment]
@pxpy Could you please show me your picture ? My email : xxbbb@vip.qq.com

**Comment by Zola** [comment]
I was verified that jpeg format supported.

something wrong  when I add argument  -- alpha

```
$python encode.py --image ori.jpg --watermark watermark.jpg --result res.jpg --alpha 5
Traceback (most recent call last):
  File "encode.py", line 55, in <module>
    main()
  File "encode.py", line 31, in main
    encode(img, wm, res, alpha)
  File "encode.py", line 50, in encode
    res_f = img_f + alpha * tmp
TypeError: ufunc 'multiply' did not contain a loop with signature matching types dtype('S32') dtype('S32') dtype('S32')
```

**Comment by linyacool** [comment]
@Zola Sorry for that, now I have fixed it.

**Comment by yejunlei2008** [comment]
The Python3 version of the blind watermark can be used, but it has no effect. It is not the image range is wrong or the watermark cannot be loaded. I hope I can fix it, or I need to know which libraries need to be installed.
