### ISSUE TITLE
另一个盲水印代码，供参考

### ISSUE THREAD

**Issue by Zola** [linyacool/blind-watermark#2]
另一个盲水印代码
https://github.com/chishaxie/BlindWaterMark

体验过程中发现，居然处理时间要10秒以上，你的代码处理图片则超级快，但水印不是对称的。

**Comment by linyacool** [comment]
@Zola 哈，其实可以是对称的，我只解码了上面一半，下面留空了，原理应该都是一样的。

**Comment by Zola** [comment]
@linyacool 那我再看看你的代码与他的代码之间的差异，谢谢你 ：）
